#  MyLoc Docker file(1)                                                              #
#        myloc-server --> soca/isoin-iot-server   (expose 3000 http)                 #

FROM node:alpine

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY ../package.json /app
RUN npm install

# Bundle app source
COPY .. /app

EXPOSE 3000
CMD [ "npm", "start" ]