#  MyApp Docker Containers (5)                                                                #
#        myloc-assets --> myloc/myloc-rest-assets                                             #
#        myloc-server --> myloc/myloc-rest-server   (expose 8080 http)                        #
#        myloc-database --> mongodb:5.7  (expose 8090)                                        #
#        myloc-database-data --> tianon/true "Map volume to containers"                       #
#        <"noname" distribution-data-container> --> soca/isoin-iot-database-data-volume       #
#                                                                                             #

FROM node:alpine

# Create app directory
RUN mkdir /app
WORKDIR /app

# Install app dependencies
COPY ../package.json /app
RUN npm install

# Bundle app source
COPY .. /app

EXPOSE 3000
CMD [ "npm", "start" ]
